#!/usr/bin/env node
// Reads all app HTML files and writes apps-data.js with them embedded as JS strings.
const fs = require('fs');
const path = require('path');

const apps = [
    'script/Apps/Cine/index.html',
    'script/Apps/Spotify/index.html',
    'script/Apps/Ps5/index.html',
    'script/Apps/Web/index.html',
    'script/Apps/Discord/index.html',
    'script/Apps/Roblox/index.html',
    'script/Apps/Android/index.html',
    'script/Apps/Cini/index.html',
    'script/Apps/VM/index.html',
    'script/Apps/Crunchy/index.html',
    'script/Apps/Geforce/index.html',
    'script/Apps/Fortnite/index.html',
    'script/Apps/RocketL/index.html',
    'script/Apps/Xbox/index.html',
];

let out = '// Auto-generated by generate-apps.js - DO NOT EDIT MANUALLY\n// Run: node generate-apps.js\n\nvar APP_HTML = {\n';

for (const p of apps) {
    const html = fs.readFileSync(path.join(__dirname, p), 'utf8');
    // Escape for JSON string embedding
    const escaped = JSON.stringify(html);
    out += `    ${JSON.stringify(p)}: ${escaped},\n`;
}

out += '};\n';

fs.writeFileSync(path.join(__dirname, 'apps-data.js'), out, 'utf8');
console.log('apps-data.js generated, size:', out.length, 'bytes');
